xcpretty: Support modern build system.
Lightricks/xcpretty pull request #13
Opened 2019-07-17 13:28 UTC by byohay

2019-07-22 09:03 UTC, DekelAvrahami requested changes
Fix and squash.

2019-07-22 09:03 UTC, DekelAvrahami commented on lib/xcpretty/formatters/formatter.rb
> -    def format_analyze(file_name, file_path);                  EMPTY; end
I think it will be clearer to separate the declarations of old build system methods (for example `format_xxx_target` or `format_check_dependencies`) from the rest. It is confusing that  we have both `format_analyze_target`  and `format_analyze` that has the build target as input. If `format_analyze_target` was separated (together with other old build system methods) under old build system comment it think it was clearer.

2019-07-22 09:03 UTC, DekelAvrahami commented on lib/xcpretty/parser.rb
> +    # $1 = file_name
`1`->`2` (and move below `file_path`).

2019-07-22 09:03 UTC, DekelAvrahami commented on lib/xcpretty/parser.rb
> +    PHASE_SCRIPT_EXECUTION_MATCHER = /^PhaseScriptExecution\s((?:\\\ |\S)*)\s*[^(]*/.freeze
Was this changed by mistake?

2019-07-22 09:04 UTC, DekelAvrahami requested changes

2019-07-22 09:04 UTC, DekelAvrahami commented on lib/xcpretty/formatters/simple.rb
> +      return "[" + build_target + "] " + formatted_text if build_target
You can make this and next line one liner by using the `?:` operator.

2019-07-22 11:43 UTC, byohay commented
@DekelAvrahami roud complete.

2019-07-23 07:31 UTC, byohay commented
@DekelAvrahami round complete.

2019-07-25 06:54 UTC, DekelAvrahami approved these changes
Squash and merge.

2019-07-25 07:32 UTC, merged